### ISSUE TITLE
Complemento arroja error de "Valor de potencia no es valido"

### ISSUE THREAD

**Issue by samtux** [dalxder/proyectoIDF#5]
Complemento arroja error de "Valor de potencia no es valido" al intentar generar la interpolacion, sea seleccionado la coordenada del mapa o de la lista de coordenadas.

Sistema operativo de prueba Arch Linux x64 bits
Versión de QGIS: 2.18.13

**Comment by dalxder** [comment]
Este error ya ha sido corregido. Gracias.
